name: Smoke Test (Actions + Pages)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "Actions is working on $GITHUB_REF at $(date -u)"

  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Make public-reports
        run: |
          mkdir -p public-reports/latest
          echo '{"ok":true,"ts":"'"$(date -u +"%Y-%m-%dT%H:%M:%SZ")"'"}' > public-reports/latest/index.json
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public-reports
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
